name: publish.yml
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: pypi

    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: astral-sh/setup-uv@v5

      - name: Build
        run: uv build

      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1